CREATE DATABASE DiemA
GO

USE DiemA
GO

CREATE TABLE TypeHv(
	Id INT,
	Name nvarchar(255) NOT NULL,
	
	PRIMARY KEY(Id)
)
GO

CREATE TABLE Gender (
	Id INT,
	Name nvarchar(255) NOT NULL,

	PRIMARY KEY(Id)
)
GO

CREATE TABLE NguoiDung (
	Id INT,
	Name NVARCHAR(255) NOT NULL DEFAULT NULL,
	DateOfBirth DATE NOT NULL,
	Gender INT NOT NULL DEFAULT 1, --nam
	Phone VARCHAR(10) NOT NULL UNIQUE,
	Email VARCHAR(255) NOT NULL UNIQUE,
	Password VARCHAR(255) NOT NULL,
	TypeHv INT NOT NULL DEFAULT 1,
	Note NVARCHAR(255) DEFAULT NULL,

	PRIMARY KEY(Id),
	FOREIGN KEY (TypeHv) REFERENCES TypeHv(Id),
	FOREIGN KEY (Gender) REFERENCES Gender(Id)
)
go

CREATE TABLE GiangVien (
	Id INT,
	Name nvarchar(255) NOT NULL DEFAULT NULL,
	DateOfBirth DATE NOT NULL,
	Gender INT NOT NULL DEFAULT 1, --nam
	Phone VARCHAR(10) NOT NULL UNIQUE,
	Email VARCHAR(255) NOT NULL UNIQUE,
	Password VARCHAR(255) NOT NULL,
	TypeHv INT NOT NULL DEFAULT 2,
	Note Nvarchar(255) DEFAULT NULL,

	PRIMARY KEY(Id),
	FOREIGN KEY (TypeHv) REFERENCES TypeHv(Id),
	FOREIGN KEY (Gender) REFERENCES Gender(Id)
)
go

CREATE TABLE Level(
	Id INT,
	Name Nvarchar(255) NOT NULL DEFAULT NULL,

	PRIMARY KEY(Id),
)
GO

CREATE TABLE KhoaHoc(
	Id INT,
	Name NVARCHAR(255) NOT NULL DEFAULT NULL,
	Level INT NOT NULL DEFAULT 1,
	GiangVien INT NOT NULL,
	HocPhi FLOAT NOT NULL DEFAULT 0,
	NgayBatDau DATE,
	NgayKetThuc DATE,
	Ghichu nvarchar(255),

	PRIMARY KEY(Id),
	FOREIGN KEY (Level) REFERENCES Level(Id),
	FOREIGN KEY (GiangVien) REFERENCES GiangVien(Id)
)
GO

create table BaiHoc(
	Id INT,
	Name Nvarchar(255) NOT NULL DEFAULT NULL,
	KhoaHocId INT,
	Link VARCHAR(255),
	Ghichu NVARCHAR(255),

	PRIMARY KEY(Id),
	FOREIGN KEY (KhoaHocId) REFERENCES KhoaHoc(Id)
)
GO

CREATE TABLE PhanLoaiDh(
	Id INT,
	Name Nvarchar(255) NOT NULL DEFAULT NULL,

	PRIMARY KEY(Id)
)
GO

CREATE TABLE NganhDaoTao(
	Id INT,
	Name NVARCHAR(255) NOT NULL DEFAULT NULL,

	PRIMARY KEY(Id),
)
GO

CREATE TABLE Truong(
	Id INT,
	Name NVARCHAR(255) NOT NULL DEFAULT NULL,
	Address NVARCHAR(255) DEFAULT NULL,
	Website NVARCHAR(255) DEFAULT NULL,
	ThongTinChiTiet NVARCHAR(255),
	ThongTinCoBan NVARCHAR(255),
	GiaTien FLOAT DEFAULT 0,
	NganhDaoTao INT DEFAULT 1,

	PRIMARY KEY(Id),
	FOREIGN KEY (NganhDaoTao) REFERENCES NganhDaoTao(Id),
)
GO

CREATE TABLE DuHoc(
	Id INT,
	SchoolId INT,
	PhanLoaiDh INT DEFAULT 1,
	GhiChu NVARCHAR(255),

	PRIMARY KEY(Id),
	FOREIGN KEY (SchoolId) REFERENCES Truong(Id),
	FOREIGN KEY (PhanLoaiDh) REFERENCES PhanLoaiDh(Id),
)
GO

ALTER TABLE KhoaHoc
DROP COLUMN NgayKetThuc
GO

ALTER TABLE Truong ADD ImageLink VARCHAR(255)
GO

ALTER TABLE Truong ADD GhiChu NVARCHAR(255) NULL DEFAULT NULL
GO

ALTER TABLE KhoaHoc ADD ImageLink VARCHAR(255) 
GO

ALTER TABLE KhoaHoc ADD GioiThieu VARCHAR(255) 
GO

ALTER TABLE GiangVien ADD GioiThieu VARCHAR(255) 
GO

ALTER TABLE BaiHoc ADD ThuTuBaiHoc INT UNIQUE 
GO